### ISSUE TITLE
Initializers are deprecated

### ISSUE THREAD

**Issue by carsonoid** [domoinc/kube-valet#8]
Kube-valet currently requires Initializers in order to work. Initializers have been abandoned and deprecated in favor of [MutatingAdmissionWebhooks](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook).

Valet should be updated to work with webhooks so that it can be used in modern clusters with a fully supported feature.

**Comment by from-nibly** [comment]
Should we close this?

**Comment by cryonex** [comment]
Yes, our good friend @carsonoid migrated to MutatingWebhooks in #9
